/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import codigos.Comodo;
import codigos.Grafo_Comodo;
import static java.lang.Character.toUpperCase;
import Views.Animacao;

/**
 *
 * @author caio_
 */
public class Principal extends javax.swing.JFrame {

    char inicial;
    char objetivo;

    public Principal() {
        initComponents();
        Grafo_Comodo grafo = new Grafo_Comodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        btnProfundidade = new javax.swing.JButton();
        btnLargura = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxInicial = new javax.swing.JComboBox<>();
        ComboBoxFinal = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("Aspirador de Pó"); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitulo.setText("Busca em Largura e Profundidade");

        btnProfundidade.setText("Busca em Profundidade");
        btnProfundidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfundidadeActionPerformed(evt);
            }
        });

        btnLargura.setText("Busca em Largura");
        btnLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLarguraActionPerformed(evt);
            }
        });

        txt.setText("Comôdo Inicial:");

        txt2.setText("Comôdo Final:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Uso de Memoria:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tempo de Execução:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Log de Expansão:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planta-mapeada.png"))); // NOI18N

        jButton1.setText("Visualizar Matriz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("nanosegundos");

        ComboBoxInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "D", "E", "F", "G", "H", "I", "J", "L", "M", "N", "O", "P", "Q", "R", "T", "U", "V", "X", "Z", "Y", "W", "K", "a", "b", "c", "d" }));
        ComboBoxInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxInicialActionPerformed(evt);
            }
        });

        ComboBoxFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "D", "E", "F", "G", "H", "I", "J", "L", "M", "N", "O", "P", "Q", "R", "T", "U", "V", "X", "Z", "Y", "W", "K", "a", "b", "c", "d" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProfundidade)
                        .addGap(18, 18, 18)
                        .addComponent(btnLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(txtTitulo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboBoxFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt)
                            .addComponent(ComboBoxInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2)
                            .addComponent(ComboBoxFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProfundidade)
                            .addComponent(btnLargura)
                            .addComponent(jButton1))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tempo)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Opções");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLarguraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProfundidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfundidadeActionPerformed
        objetivo = codigos.Grafo_Comodo.retornaLetra(ComboBoxInicial.getItemCount());
        inicial = codigos.Grafo_Comodo.retornaLetra(ComboBoxFinal.getItemCount());

        Grafo_Comodo grafo = new Grafo_Comodo();
        grafo.setComodos(new Comodo('A')); // 0
        grafo.setComodos(new Comodo('B')); // 1
        grafo.setComodos(new Comodo('C')); // 2
        grafo.setComodos(new Comodo('D')); // 3
        grafo.setComodos(new Comodo('E')); // 4
        grafo.setComodos(new Comodo('F')); // 5
        grafo.setComodos(new Comodo('G')); // 6
        grafo.setComodos(new Comodo('H')); // 7 
        grafo.setComodos(new Comodo('I')); // 8 
        grafo.setComodos(new Comodo('J')); // 9
        grafo.setComodos(new Comodo('L')); // 10
        grafo.setComodos(new Comodo('M')); // 11
        grafo.setComodos(new Comodo('N')); // 12
        grafo.setComodos(new Comodo('O')); // 13
        grafo.setComodos(new Comodo('P')); // 14
        grafo.setComodos(new Comodo('Q')); // 15
        grafo.setComodos(new Comodo('R')); // 16
        grafo.setComodos(new Comodo('S')); // 17
        grafo.setComodos(new Comodo('T')); // 18
        grafo.setComodos(new Comodo('U')); // 19
        grafo.setComodos(new Comodo('V')); // 20
        grafo.setComodos(new Comodo('X')); // 21
        grafo.setComodos(new Comodo('Z')); // 22
        grafo.setComodos(new Comodo('Y')); // 23
        grafo.setComodos(new Comodo('W')); // 24
        grafo.setComodos(new Comodo('K')); // 25
        grafo.setComodos(new Comodo('a')); // 26
        grafo.setComodos(new Comodo('b')); // 27
        grafo.setComodos(new Comodo('c')); // 28

        int ini = grafo.retornaIndice(inicial);
        int end = grafo.retornaIndice(objetivo);
        long tempoInicial = System.nanoTime();
        grafo.buscaEmProfundidade(ini, end);
        long tempoFinal = System.nanoTime();
        tempo.setText(Double.toString(tempoFinal - tempoInicial));
        String teste = "";
        
        //LOG COMPLETO DE EXPANSÃO
        for (int x = 0; grafo.rota.length > x; x++) {

            for (int y = 0; y < 2; y++) {
                if (y == 0 && grafo.rota[x][y] != -1) {
                    teste += "[";
                }
                if (grafo.rota[x][y] != -1) {
                    teste += " " + grafo.retornaLetra(grafo.rota[x][y]) + " ";
                }
                if (y == 1 && grafo.rota[x][y] != -1) {
                    teste += "] \n";
                }

            }

        }
        jTextArea1.setText(teste);
        String[] resultado = grafo.rota_objetivo.split(";");
        int[][] rota_ob = new int[20][2];
        for (int x = 0; x < 20; x++) {
            for (int y = 0; y < 2; y++) {
                rota_ob[x][y] = -1;
            }
        }
        int y = 0;
        for (int x = 0; resultado.length > x; x++) {
            if (resultado.length > y) {
                rota_ob[x][0] = Integer.parseInt(resultado[y]);
                rota_ob[x][1] = Integer.parseInt(resultado[++y]);
                y++;
            }

        }

        Animacao ani = new Animacao(ini,rota_ob);


    }//GEN-LAST:event_btnProfundidadeActionPerformed

    private void ComboBoxInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFinal;
    private javax.swing.JComboBox<String> ComboBoxInicial;
    private javax.swing.JButton btnLargura;
    private javax.swing.JButton btnProfundidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel tempo;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
